name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: openjdk:8-jdk
      options: --user root
    steps:
      - name: checkout repository
      - uses: actions/checkout@v1
      - name: validate gradle wrapper
      - uses: gradle/wrapper-validation-action@v1
      - name: build
        run: ./gradlew checkLicenses build
      - name: capture build artifacts
        if: ${{ matrix.java == '1.8' }}
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
